const Database = require('better-sqlite3');
const path = require('path');
const fs = require('fs');

const DB_PATH = path.join(__dirname, '..', 'storyforge.db');

// ── Table definitions extracted from src/lib/db/schema.ts v37 ──
// Phase 1: document-store approach — all content columns are TEXT (JSON internally)
// Phase 2+: type-aware columns derived from TS types
const TABLES = {
  projects: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'name TEXT NOT NULL DEFAULT ""',
    'genre TEXT NOT NULL DEFAULT ""',
    'genres TEXT NOT NULL DEFAULT "[]"',
    'status TEXT NOT NULL DEFAULT "drafting"',
    'description TEXT NOT NULL DEFAULT ""',
    'targetWordCount INTEGER NOT NULL DEFAULT 0',
    'currentWordCount INTEGER DEFAULT 0',
    'coverImage TEXT DEFAULT NULL',
    'writingStyleId TEXT DEFAULT NULL',
    'methodologyId TEXT DEFAULT NULL',
    'creativeMode TEXT DEFAULT NULL',
    'enableMultiWorld INTEGER NOT NULL DEFAULT 0',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
    'data TEXT NOT NULL DEFAULT "{}"',
  ],
  worldviews: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  storyCores: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  powerSystems: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  characters: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'name TEXT NOT NULL DEFAULT ""',
    'role TEXT NOT NULL DEFAULT "minor"',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  outlineNodes: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'parentId INTEGER DEFAULT NULL',
    'sortOrder INTEGER NOT NULL DEFAULT 0',
    'type TEXT NOT NULL DEFAULT "chapter"',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  chapters: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'outlineNodeId INTEGER DEFAULT NULL',
    'sortOrder INTEGER NOT NULL DEFAULT 0',
    'status TEXT NOT NULL DEFAULT "draft"',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  foreshadows: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'status TEXT NOT NULL DEFAULT "pending"',
    'type TEXT NOT NULL DEFAULT ""',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  geographies: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  histories: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  creativeRules: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  characterRelations: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'fromCharacterId INTEGER NOT NULL',
    'toCharacterId INTEGER NOT NULL',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  snapshots: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'type TEXT NOT NULL DEFAULT ""',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
  ],
  references: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'type TEXT NOT NULL DEFAULT ""',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  promptTemplates: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'scope TEXT NOT NULL DEFAULT "system"',
    'moduleKey TEXT NOT NULL DEFAULT ""',
    'isActive INTEGER NOT NULL DEFAULT 1',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  detailedOutlines: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'outlineNodeId INTEGER DEFAULT NULL',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  importJobs: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'type TEXT NOT NULL DEFAULT ""',
    'status TEXT NOT NULL DEFAULT "pending"',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  promptWorkflows: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'scope TEXT NOT NULL DEFAULT "system"',
    'isDefault INTEGER NOT NULL DEFAULT 0',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  importSessions: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'status TEXT NOT NULL DEFAULT "pending"',
    'fileHash TEXT DEFAULT NULL',
    'targetWorldGroupId INTEGER DEFAULT NULL',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  importLogs: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'sessionId INTEGER NOT NULL',
    'chunkIndex INTEGER NOT NULL DEFAULT 0',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
  ],
  importFiles: [
    'sessionId INTEGER PRIMARY KEY',
    'fileHash TEXT DEFAULT NULL',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
  ],
  stateCards: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'category TEXT NOT NULL DEFAULT ""',
    'entityName TEXT NOT NULL DEFAULT ""',
    'lastChapterId INTEGER DEFAULT NULL',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  emotionBeatCards: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'chapterId INTEGER DEFAULT NULL',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  referenceChunkAnalysis: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'referenceId INTEGER NOT NULL',
    'chunkIndex INTEGER NOT NULL DEFAULT 0',
    'data TEXT NOT NULL DEFAULT "{}"',
  ],
  worldNodes: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'parentId INTEGER DEFAULT NULL',
    'sortOrder INTEGER NOT NULL DEFAULT 0',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  storyArcs: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'type TEXT NOT NULL DEFAULT ""',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  notes: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'chapterId INTEGER DEFAULT NULL',
    'pinned INTEGER NOT NULL DEFAULT 0',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  historicalTimelineEvents: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'era TEXT DEFAULT NULL',
    'year TEXT DEFAULT NULL',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  historicalKeywords: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'category TEXT DEFAULT NULL',
    'era TEXT DEFAULT NULL',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  importantLocations: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'parentId INTEGER DEFAULT NULL',
    'sortOrder INTEGER NOT NULL DEFAULT 0',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  worldRulesProfiles: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL UNIQUE',
    'worldGroupId INTEGER DEFAULT NULL',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  worldGroups: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'type TEXT NOT NULL DEFAULT ""',
    'sortOrder INTEGER NOT NULL DEFAULT 0',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  worldGroupLinks: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'fromGroupId INTEGER NOT NULL',
    'toGroupId INTEGER NOT NULL',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  itemLedger: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'itemName TEXT NOT NULL DEFAULT ""',
    'chapterId INTEGER DEFAULT NULL',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  storyTimelineEvents: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'chapterId INTEGER DEFAULT NULL',
    'sortOrder INTEGER NOT NULL DEFAULT 0',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  codexCategories: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'domain TEXT NOT NULL DEFAULT ""',
    'parentId INTEGER DEFAULT NULL',
    'builtInKey TEXT DEFAULT NULL',
    'worldGroupId INTEGER DEFAULT NULL',
    'sortOrder INTEGER NOT NULL DEFAULT 0',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  codexEntries: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'categoryId INTEGER DEFAULT NULL',
    'worldGroupId INTEGER DEFAULT NULL',
    'sortOrder INTEGER NOT NULL DEFAULT 0',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  aiUsageLog: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'timestamp INTEGER NOT NULL DEFAULT 0',
    'category TEXT DEFAULT NULL',
    'model TEXT DEFAULT NULL',
    'data TEXT NOT NULL DEFAULT "{}"',
  ],
  userStyleProfiles: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  temporalFacts: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'worldGroupId INTEGER DEFAULT NULL',
    'characterId INTEGER DEFAULT NULL',
    'locationId INTEGER DEFAULT NULL',
    'codexEntryId INTEGER DEFAULT NULL',
    'predicate TEXT NOT NULL DEFAULT ""',
    'status TEXT NOT NULL DEFAULT "candidate"',
    'sourceChapterId INTEGER DEFAULT NULL',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  retrievalChunks: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'worldGroupId INTEGER DEFAULT NULL',
    'sourceChapterId INTEGER DEFAULT NULL',
    'data TEXT NOT NULL DEFAULT "{}"',
  ],
  narrativeSummaryNodes: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'worldGroupId INTEGER DEFAULT NULL',
    'level TEXT NOT NULL DEFAULT "chapter"',
    'sourceChapterId INTEGER DEFAULT NULL',
    'sourceOutlineNodeId INTEGER DEFAULT NULL',
    'status TEXT NOT NULL DEFAULT "pending"',
    'data TEXT NOT NULL DEFAULT "{}"',
  ],
  // ── v3.9.1 新增表（16 张，document-store 模式）──
  referenceAnalysisRuns: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  referenceAnalysisSources: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  cultivationSystems: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'name TEXT DEFAULT NULL',
    'worldGroupId INTEGER DEFAULT NULL',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  cultivationProgress: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'worldGroupId INTEGER DEFAULT NULL',
    'characterId INTEGER DEFAULT NULL',
    'cultivationSystemId INTEGER DEFAULT NULL',
    'sourceChapterId INTEGER DEFAULT NULL',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  characterDrivenPlans: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'name TEXT DEFAULT NULL',
    'status TEXT DEFAULT NULL',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  inspirationWorkspaces: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  knowledgeLedger: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'worldGroupId INTEGER DEFAULT NULL',
    'characterId INTEGER DEFAULT NULL',
    'sourceChapterId INTEGER DEFAULT NULL',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  storylineProgress: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'arcId INTEGER DEFAULT NULL',
    'lastActiveChapterId INTEGER DEFAULT NULL',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  storylineCrossings: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'arcIdA INTEGER DEFAULT NULL',
    'arcIdB INTEGER DEFAULT NULL',
    'chapterId INTEGER DEFAULT NULL',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  agentConversations: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'worldGroupId INTEGER DEFAULT NULL',
    'title TEXT DEFAULT NULL',
    'status TEXT DEFAULT NULL',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  agentEvents: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'conversationId INTEGER DEFAULT NULL',
    'sequence INTEGER DEFAULT NULL',
    'kind TEXT DEFAULT NULL',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  nodeFlows: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  nodeRuns: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  simulationSessions: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'worldGroupId INTEGER DEFAULT NULL',
    'kind TEXT DEFAULT NULL',
    'status TEXT DEFAULT NULL',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  simulationEvents: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'sessionId INTEGER DEFAULT NULL',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
  simulationCheckpoints: [
    'id INTEGER PRIMARY KEY AUTOINCREMENT',
    'projectId INTEGER NOT NULL',
    'sessionId INTEGER DEFAULT NULL',
    'data TEXT NOT NULL DEFAULT "{}"',
    'createdAt INTEGER NOT NULL',
    'updatedAt INTEGER NOT NULL',
  ],
};

function initDb() {
  const dbDir = path.dirname(DB_PATH);
  if (!fs.existsSync(dbDir)) {
    fs.mkdirSync(dbDir, { recursive: true });
  }

  const db = new Database(DB_PATH);
  db.pragma('journal_mode = WAL');
  db.pragma('foreign_keys = ON');

  for (const [tableName, columns] of Object.entries(TABLES)) {
    const sql = `CREATE TABLE IF NOT EXISTS "${tableName}" (\n  ${columns.join(',\n  ')}\n)`;
    db.exec(sql);
  }

  // 2026-08-09 P2: 清理上游已废弃表（Dexie v29/v31+ 置 null 删除后不再创建）。
  // factions/itemSystems(v29 词条化)、master*(v31+ 作品分析表) 均为空表，DROP 幂等安全。
  const DROPPED_TABLES = [
    'factions', 'itemSystems',
    'masterWorks', 'masterChapterBeats', 'masterChunkAnalysis',
    'masterStyleMetrics', 'masterInsights',
  ];
  for (const t of DROPPED_TABLES) {
    db.exec(`DROP TABLE IF EXISTS "${t}"`);
  }

  return db;
}

module.exports = { initDb, TABLES, DB_PATH };
